package lockfile

import (
	"os"
	"path/filepath"
	"testing"
)

func TestNpmLockFile(t *testing.T) {
	tests := []struct {
		name        string
		content     string
		expectError bool
		expectedLen int
		check       func(deps []Dependency) error
	}{
		{
			name: "lockfileVersion 2",
			content: `{
  "name": "test-project",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "packages": {
    "": {"name": "test-project", "version": "1.0.0"},
    "node_modules/lodash": {
      "version": "4.17.21",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
    },
    "node_modules/express": {
      "version": "4.18.2",
      "resolved": "https://registry.npmjs.org/express/-/express-4.18.2.tgz"
    }
  }
}`,
			expectError: false,
			expectedLen: 2,
			check: func(deps []Dependency) error {
				found := toMap(deps)
				if !found["lodash"] {
					return errTest("missing lodash")
				}
				if !found["express"] {
					return errTest("missing express")
				}
				return nil
			},
		},
		{
			name: "lockfileVersion 1",
			content: `{
  "name": "test-project",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "dependencies": {
    "lodash": {
      "version": "4.17.21",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
    },
    "express": {
      "version": "4.18.2",
      "resolved": "https://registry.npmjs.org/express/-/express-4.18.2.tgz"
    }
  }
}`,
			expectError: false,
			expectedLen: 2,
		},
		{
			name:        "invalid JSON",
			content:     `{invalid}`,
			expectError: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			lockPath := filepath.Join(tmpDir, "package-lock.json")
			if err := os.WriteFile(lockPath, []byte(tt.content), 0644); err != nil {
				t.Fatal(err)
			}

			lf, err := NewNpmLockFile(tmpDir)
			if err != nil {
				if !tt.expectError {
					t.Fatalf("NewNpmLockFile failed: %v", err)
				}
				return
			}

			if lf.Type() != "npm" {
				t.Errorf("Expected type 'npm', got '%s'", lf.Type())
			}

			deps, err := lf.Dependencies()
			if err != nil {
				if !tt.expectError {
					t.Fatalf("Dependencies failed: %v", err)
				}
				return
			}

			if len(deps) != tt.expectedLen {
				t.Errorf("Expected %d deps, got %d", tt.expectedLen, len(deps))
			}

			if tt.check != nil {
				if err := tt.check(deps); err != nil {
					t.Error(err)
				}
			}
		})
	}
}

func TestGoLockFile(t *testing.T) {
	sumContent := `github.com/gin-gonic/gin v1.9.1 h1:abc123=
github.com/gin-gonic/gin v1.9.1/go.mod h1:def456=
github.com/stretchr/testify v1.8.4 h1:ghi789=
github.com/stretchr/testify v1.8.4/go.mod h1:jkl012=
`

	tmpDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(tmpDir, "go.sum"), []byte(sumContent), 0644); err != nil {
		t.Fatal(err)
	}

	lf, err := NewGoLockFile(tmpDir)
	if err != nil {
		t.Fatalf("NewGoLockFile failed: %v", err)
	}

	if lf.Type() != "go" {
		t.Errorf("Expected type 'go', got '%s'", lf.Type())
	}

	deps, err := lf.Dependencies()
	if err != nil {
		t.Fatalf("Dependencies failed: %v", err)
	}

	// go.sum 中每个包有 h1: 和 go.mod 两行，去重后返回 2 个
	if len(deps) != 2 {
		t.Errorf("Expected 2 deps, got %d", len(deps))
	}

	found := toMap(deps)
	if !found["github.com/gin-gonic/gin"] {
		t.Error("missing gin")
	}
	if !found["github.com/stretchr/testify"] {
		t.Error("missing testify")
	}
}

func TestRustLockFile(t *testing.T) {
	lockContent := `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.193"

[[package]]
name = "tokio"
version = "1.35.0"

[[package]]
name = "my-project"
version = "0.1.0"
`

	tmpDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(tmpDir, "Cargo.lock"), []byte(lockContent), 0644); err != nil {
		t.Fatal(err)
	}

	lf, err := NewRustLockFile(tmpDir)
	if err != nil {
		t.Fatalf("NewRustLockFile failed: %v", err)
	}

	if lf.Type() != "cargo" {
		t.Errorf("Expected type 'cargo', got '%s'", lf.Type())
	}

	deps, err := lf.Dependencies()
	if err != nil {
		t.Fatalf("Dependencies failed: %v", err)
	}

	if len(deps) != 3 {
		t.Errorf("Expected 3 deps, got %d", len(deps))
	}

	found := toMap(deps)
	if !found["serde"] {
		t.Error("missing serde")
	}
	if !found["tokio"] {
		t.Error("missing tokio")
	}
}

func TestDetectLockFile(t *testing.T) {
	tests := []struct {
		name        string
		setup       func(string) error
		expectType  string
		expectError bool
	}{
		{
			name: "npm lockfile",
			setup: func(dir string) error {
				return os.WriteFile(filepath.Join(dir, "package-lock.json"), []byte("{}"), 0644)
			},
			expectType:  "npm",
			expectError: false,
		},
		{
			name: "go lockfile",
			setup: func(dir string) error {
				return os.WriteFile(filepath.Join(dir, "go.sum"), []byte(""), 0644)
			},
			expectType:  "go",
			expectError: false,
		},
		{
			name:        "no lockfile",
			setup:       func(dir string) error { return nil },
			expectType:  "",
			expectError: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			if err := tt.setup(tmpDir); err != nil {
				t.Fatal(err)
			}

			lf, err := DetectLockFile(tmpDir)
			if err != nil {
				if !tt.expectError {
					t.Fatalf("DetectLockFile failed: %v", err)
				}
				return
			}

			if lf.Type() != tt.expectType {
				t.Errorf("Expected type '%s', got '%s'", tt.expectType, lf.Type())
			}
		})
	}
}

// Helper functions
type testError string

func (e testError) Error() string { return string(e) }

func errTest(msg string) error { return testError(msg) }

func toMap(deps []Dependency) map[string]bool {
	m := make(map[string]bool)
	for _, d := range deps {
		m[d.Name] = true
	}
	return m
}
